import test from 'node:test';
import assert from 'node:assert/strict';
import {IleumTissue} from '../src/ileum-host.mjs';
import {ManualTissue} from '../src/manual-host.mjs';
import {parseIleumPrompt,ILEUM_MANIFEST} from '../src/ileum-parameters.mjs';
const run=(t,minutes)=>{while(minutes>0){const n=Math.min(minutes,60);t.step(n);minutes-=n;}return t;};
const near=(a,b=0)=>assert.ok(Math.abs(a-b)<1e-8,`${a} differs from ${b}`);
function conserved(t){const a=t.auditLab();assert.equal(a.bacteria.residual,0);near(a.water.residual);near(a.water.systemResidual);for(const p of t.lab.patches)for(const k of ['water'])assert.ok(Number.isFinite(p[k])&&p[k]>=-1e-12);}
function fixture(){const t=new IleumTissue(7);t.inject('epec');const b=t.lab.bacteria[0],cells=t.cells.filter(c=>c.type==='macrophage').slice(0,2);b.compartment='basal';for(const c of cells){c.x=b.x;c.y=b.y;c.lab.compartment='basal';}return {t,b,c:cells[0],other:cells[1]};}
test('quiet ileum retains 100 cells, six reserves, intact barrier and no invented inflammation',()=>{const t=run(new IleumTissue(),120);assert.equal(t.cells.length,100);assert.equal(t.metrics.reserve,6);assert.equal(t.metrics.barrier,1);assert.equal(t.fields.amount('TNF'),0);assert.equal(t.lab.events.length,0);conserved(t);});
test('reference host remains separate and exposes only its original two handlers',()=>{const t=new ManualTissue();assert.equal(t.export().coverage.implemented,2);assert.equal(t.lab,undefined);assert.throws(()=>t.inject('epec'));});
test('parsing distinguishes pathogen mechanism, ileitis and controls without mutation',()=>{for(const [text,kind]of [['EPEC on the left','epec'],['EPEC attachment off','epec_control'],['Persistent ileitis','ileitis'],['Restore resolution','regulation']])assert.equal(parseIleumPrompt(text).kind,kind);assert.equal(parseIleumPrompt('Shiga toxin CASP4').valid,false);});
test('invalid intervention is atomic and does not consume RNG',()=>{const t=new IleumTissue(),before=JSON.stringify(t.export());assert.throws(()=>t.inject('epec',NaN));assert.throws(()=>t.inject('epec',.25,Infinity));assert.equal(JSON.stringify(t.export()),before);});
test('EPEC inoculum is apical, finite and noninvasive; no automatic tissue damage at injection',()=>{const t=new IleumTissue();t.inject('epec');assert.equal(t.lab.bacteria.length,24);assert.ok(t.lab.bacteria.every(b=>b.state==='free'&&b.compartment==='apical'));assert.equal(t.metrics.barrier,1);assert.equal(t.lab.events.length,0);conserved(t);});
test('phagocytosis requires same compartment and physical reach',()=>{const {t,b,c}=fixture();b.compartment='apical';assert.throws(()=>t.startEvent('ILEUM_PHAGOCYTOSIS',c.id,b.id));b.compartment='basal';c.x=b.x+.3;assert.throws(()=>t.startEvent('ILEUM_PHAGOCYTOSIS',c.id,b.id));});
test('exclusive target reservation prevents simultaneous double ingestion',()=>{const {t,b,c,other}=fixture();t.startEvent('ILEUM_PHAGOCYTOSIS',c.id,b.id);assert.throws(()=>t.startEvent('ILEUM_PHAGOCYTOSIS',other.id,b.id));assert.equal(t.lab.events.length,1);});
test('engulfment waits for completion, moves one target into cargo and is idempotent',()=>{const {t,b,c}=fixture();const record=t.startEvent('ILEUM_PHAGOCYTOSIS',c.id,b.id),e=t.lab.events.find(e=>e.id===record.id);assert.equal(t.finishEvent(e),false);assert.equal(b.state,'free');run(t,6);assert.equal(b.state,'internalized');assert.deepEqual(c.lab.cargo,[b.id]);const before=JSON.stringify(t.auditLab());t.finishEvent(e);assert.equal(JSON.stringify(t.auditLab()),before);assert.equal(t.lab.bacterialBalance.killed,0);conserved(t);});
test('processing has a distinct duration and kills cargo exactly once',()=>{const {t,b,c}=fixture();t.startEvent('ILEUM_PHAGOCYTOSIS',c.id,b.id);run(t,6);const active=t.lab.events.find(e=>e.cell_id===c.id&&e.status==='running');if(!active)t.startEvent('ILEUM_CARGO_PROCESSING',c.id,b.id);run(t,20);assert.equal(b.state,'killed');assert.ok(!c.lab.cargo.includes(b.id));assert.ok(t.lab.bacterialBalance.killed>=1);conserved(t);});
test('lost contact cancels an event and releases its reserved target',()=>{const {t,b,c}=fixture();const start=t.startEvent('ILEUM_PHAGOCYTOSIS',c.id,b.id);c.x+=.4;run(t,6);const e=t.lab.events.find(e=>e.id===start.id);assert.equal(e.status,'cancelled');assert.equal(b.owner,null);assert.equal(b.state,'free');conserved(t);});
test('vascular crossing cannot be requested without a recruitment cue',()=>{const t=new IleumTissue(),c=t.cells.find(c=>c.reserve);assert.throws(()=>t.startEvent('ILEUM_VASCULAR_CROSSING',c.id));c.lab.activation=.1;t.startEvent('ILEUM_VASCULAR_CROSSING',c.id);assert.equal(c.reserve,true);run(t,12);assert.equal(c.reserve,false);assert.equal(t.cells.length,100);assert.equal(t.metrics.recruited,1);});
test('adhesion-disabled control has no attaching/effacing injury; EPEC produces local injury and innate recruitment',()=>{for(const seed of [7,20260919]){const wild=new IleumTissue(seed),control=new IleumTissue(seed);wild.inject('epec');control.inject('epec_control');run(wild,360);run(control,360);assert.ok(wild.lab.events.some(e=>e.action_id==='ILEUM_ADHESION'&&e.status==='acknowledged'));assert.ok(wild.lab.patches.some(q=>q.brush<.8));assert.ok(wild.metrics.barrier<control.metrics.barrier);assert.ok(wild.metrics.recruited>0);assert.equal(control.metrics.barrier,1);assert.equal(control.fields.amount('TNF'),0);conserved(wild);conserved(control);}});
test('ileitis persists through the innate barrier loop without bacteria or an external TNF source',()=>{const t=new IleumTissue();t.inject('ileitis');assert.equal(t.sources.length,0);assert.equal(t.lab.bacteria.length,0);const barrier=t.metrics.barrier;run(t,600);assert.ok(t.fields.amount('TNF')>0);assert.ok(t.metrics.barrier<barrier);assert.equal(t.sources.length,0);assert.ok(t.lab.patches.some(q=>q.PAMP>.05));conserved(t);});
test('restoring resolution changes competence without resetting existing damage or fields',()=>{const t=new IleumTissue();t.inject('ileitis');run(t,60);const before=t.slots.map(s=>s.junction),tnf=t.fields.amount('TNF');t.inject('regulation');assert.ok(t.lab.patches.every(q=>q.resolution===1));assert.deepEqual(t.slots.map(s=>s.junction),before);assert.equal(t.fields.amount('TNF'),tnf);});
test('removing inputs retains bacteria and susceptibility, while stopping future inputs',()=>{const t=new IleumTissue();t.inject('epec');t.inject('ileitis');const before=t.auditLab();t.inject('resolve');assert.deepEqual(t.auditLab(),before);assert.equal(t.lab.replicationEnabled,false);assert.ok(t.lab.patches.some(p=>p.resolution<1));});
test('same seed and interventions reproduce physical states, extension events and RNG counts',()=>{const a=new IleumTissue(42),b=new IleumTissue(42);for(const t of [a,b]){t.inject('epec');run(t,120);}assert.deepEqual(a.lab,b.lab);assert.deepEqual(a.cells,b.cells);assert.deepEqual(a.auditLab(),b.auditLab());});
test('one-hour stepping and sixty one-minute steps have the same physical result',()=>{const a=new IleumTissue(42),b=new IleumTissue(42);a.inject('epec');b.inject('epec');a.step(60);for(let i=0;i<60;i++)b.step();assert.deepEqual(a.cells,b.cells);assert.deepEqual(a.lab.bacteria,b.lab.bacteria);assert.equal(a.lab.draws,b.lab.draws);assert.deepEqual(a.lab.events,b.lab.events);});
test('export carries uncalibrated assumptions, ledgers, original coverage and independent RNG provenance',()=>{const t=new IleumTissue();t.step();const out=t.export();assert.equal(out.mode,'ileum');assert.equal(out.coverage.implemented,2);assert.equal(out.extension.manifest.evidence,'P');assert.equal(out.resumable,false);assert.equal(out.counters.apiCalls,0);assert.equal(out.extension.manifest.version,ILEUM_MANIFEST.version);assert.equal(out.frames.at(-1).lab.audit.water.retained,out.extensionAudit.water.retained);});

test('innate secretion and event energy are finite and accounted',()=>{const t=new IleumTissue();t.inject('epec');run(t,360);for(const c of t.cells.filter(c=>['macrophage','neutrophil'].includes(c.type))){near(c.lab.tnfBudget+c.lab.secretedTNF,ILEUM_MANIFEST.innate.tnf_budget_NAU);assert.ok(c.lab.tnfBudget>=0);assert.ok(c.state.resources.energy>=0);const spent=t.lab.events.filter(e=>e.cell_id===c.id&&e.status==='acknowledged').reduce((a,e)=>a+e.reserved_energy,0);near(c.state.resources.energy+spent,1);}});
