import test from 'node:test';
import assert from 'node:assert/strict';
import {UnifiedTissue,parsePerturbation,HOST_ACTIONS} from '../src/unified-host.mjs';
const clone=v=>JSON.parse(JSON.stringify(v));
export const fixture=(pick=null)=>async r=>({...r,decisions:Object.fromEntries(r.cells.map(c=>{const a=pick?.(c)??c.actions[1]??'WAIT';return [c.id,{action:a,weights:Object.fromEntries(c.actions.map(k=>[k,k===a?1:0])),confidence:1,source:'Jev'}];})),meta:{calls:1,inputTokens:100,model:'fixture-not-live'}});
const state=t=>JSON.stringify({cells:t.cells,fields:t.fields.audit(),values:t.fields.values,epoch:t.epoch(),events:[...t.kernel.events],rng:t.rngDraws,lab:t.lab});
async function run(t,n,p=fixture()){while(n){const d=Math.min(n,60);await t.advance(d,p);n-=d;}}
test('single unified tissue starts at local steady state for all 100 cells',async()=>{const t=new UnifiedTissue();let calls=0;await t.advance(60,()=>{calls++;throw Error('unexpected');});assert.equal(calls,0);assert.equal(t.metrics.active,0);assert.equal(t.totalDecisions,0);assert.equal(t.fields.amount('CXCL8'),0);assert.equal(t.metrics.barrier,1);assert.equal(t.cells.length,100);assert.equal(t.metrics.reserve,8);});
test('prompts describe inputs in English, including combined perturbations',()=>{assert.deepEqual(parsePerturbation('A pathogen enters on the right').kinds,['epec']);assert.equal(parsePerturbation('A pathogen enters on the right').x,.76);assert.deepEqual(parsePerturbation('EPEC and IBD in the center').kinds,['epec','ileitis']);assert.equal(parsePerturbation('Inject CXCL8').valid,false);assert.equal(parsePerturbation('A virus enters').valid,false);});
test('preview, planning and local observation draw no RNG and change no physiology',()=>{const t=new UnifiedTissue();t.inject('epec');const before=state(t);parsePerturbation('ETEC');for(let i=0;i<3;i++)t.plan();assert.equal(state(t),before);});
test('pathogen appears immediately; only nearby cells depart; no cytokine is injected',()=>{const t=new UnifiedTissue();t.inject('epec',.25);assert.equal(t.lab.bacteria.length,24);assert(t.metrics.active>0&&t.metrics.active<20);assert.equal(t.fields.amount('TNF'),0);assert.equal(t.fields.amount('CXCL8'),0);assert.equal(t.firstDeparture.time_min,0);assert(t.cells.filter(c=>c.x>.8).every(c=>!t.local(c).active));assert(t.cells.filter(c=>c.reserve).every(c=>!t.local(c).active));});
test('healthy neighbors alone do not activate cells; local altered neighbors do',()=>{const t=new UnifiedTissue(),c=t.cells.find(c=>c.type==='macrophage'),n=t.cells.find(c=>c.type==='fibroblast');n.x=c.x;n.y=c.y;assert.equal(t.local(c).active,false);n.health=70;assert(t.local(c).reasons.includes('Altered neighboring cell'));});
test('no substitute provider is used when a manual-eligible cell needs Jev',async()=>{const t=new UnifiedTissue(),c=t.cells[0];c.state.memory.alarm=.8;c.health=80;const before=state(t);await assert.rejects(t.advance(1),/Connect Jev/);assert.equal(state(t),before);});
test('complete reply validation precedes any physical or RNG mutation',async()=>{const t=new UnifiedTissue();for(const c of t.cells.slice(0,2)){c.health=80;c.state.memory.alarm=.8;}const p=t.plan(),reply=await fixture()(p.request);reply.decisions[p.request.cells[1].id].action='NOT_PERMITTED';const before=state(t);assert.throws(()=>t.commitChoices(p,reply));assert.equal(state(t),before);});
test('stale, wrong-run and missing-cell responses cannot commit',async()=>{const t=new UnifiedTissue(),c=t.cells[0];c.health=80;c.state.memory.alarm=.8;const p=t.plan(),r=await fixture()(p.request);assert.throws(()=>t.commitChoices(p,{...r,run_id:'wrong'}));const missing=clone(r);delete missing.decisions[p.request.cells[0].id];assert.throws(()=>t.commitChoices(p,missing));t.inject('injury');const before=state(t);assert.throws(()=>t.commitChoices(p,r),/Stale/);assert.equal(state(t),before);});
test('probabilities and Jev source are verified rather than fabricated',async()=>{const t=new UnifiedTissue();t.cells[0].health=80;t.cells[0].state.memory.alarm=.8;const p=t.plan(),r=await fixture()(p.request),id=p.request.cells[0].id;r.decisions[id].weights.WAIT=.8;assert.throws(()=>t.commitChoices(p,r));r.decisions[id].weights.WAIT=0;r.decisions[id].source='local';assert.throws(()=>t.commitChoices(p,r));});
test('every queried cell receives a distinct question, no global prompt or full map',async()=>{const t=new UnifiedTissue();t.inject('epec');let questions=0;const p=fixture();await run(t,40,async r=>{assert.equal(new Set(r.cells.map(c=>c.id)).size,r.cells.length);assert(!JSON.stringify(r).includes('description'));assert(!JSON.stringify(r).includes('patches'));for(const c of r.cells)assert(c.observation.reasons.length);questions+=r.cells.length;return p(r);});assert(questions>0);assert.equal(t.decisions.length,questions);assert(t.decisions.every(d=>d.source==='Jev'));});
test('CXCL8 follows a completed Jev-chosen induction, never the prompt',async()=>{const t=new UnifiedTissue();t.inject('epec');await run(t,240);const events=[...t.kernel.events.values()].filter(e=>e.action_id==='EPITHELIAL_CXCL8_INDUCTION'&&e.status==='acknowledged');assert(events.length);assert(t.fields.amount('CXCL8')>0);for(const e of events){assert(e.acknowledged_at>=e.started_at+e.duration_min);assert(e.duration_min>=30&&e.duration_min<=360);assert(t.decisions.some(d=>d.event_id===e.id));}assert(t.history.some(f=>f.metrics.preparing>0));});
test('IBD-like injury has no injected TNF; myeloid TNF requires Jev and the manual clock',async()=>{const t=new UnifiedTissue();t.inject('ileitis');assert.equal(t.fields.amount('TNF'),0);assert.equal(t.sources.length,0);await run(t,360,fixture(c=>c.actions.includes('MYELOID_TNF_INDUCTION')?'MYELOID_TNF_INDUCTION':c.actions[1]));assert(t.decisions.some(d=>d.action==='MYELOID_TNF_INDUCTION'));assert(t.fields.amount('TNF')>0);assert(t.fields.amount('CXCL8')>0);});
test('fibroblast actions use the original manual gates and Jev, not decorative inactivity',async()=>{const t=new UnifiedTissue(),c=t.cells.find(c=>c.type==='fibroblast');t.fields.deposit('TNF',c.basal,.2);c.state.memory.stromal_alarm=.8;const p=t.plan(),row=p.entries.find(e=>e.id===c.id);assert(row.actions.includes('STROMAL_ACTIVATION'));const response=await fixture(c=>c.actions.includes('STROMAL_ACTIVATION')?'STROMAL_ACTIVATION':'WAIT')(p.request);t.commitChoices(p,response);assert.equal(t.kernel.activeEvents(c.id)[0].action_id,'STROMAL_ACTIVATION');});
test('generic injury does not invent NK target recognition or CXCL8-directed NK migration',()=>{const t=new UnifiedTissue(),c=t.cells.find(c=>c.type==='nk');c.health=70;t.fields.deposit('CXCL8',c.basal,.5);const p=t.plan().entries.find(e=>e.id===c.id);assert(!p.actions.includes('NK_CYTOTOXIC_HIT'));assert(!p.actions.includes('LYMPHOCYTE_MOTILITY'));assert(c.state.type==='nk');});
test('phagocytosis reserves one real local target, processes cargo, and applies effects once',async()=>{const t=new UnifiedTissue();t.inject('epec');const c=t.cells.find(c=>c.type==='macrophage'),b=t.lab.bacteria[0];b.x=c.x;b.y=c.y;b.compartment='basal';const provider=fixture(c=>c.actions.includes('PHAGOCYTOSIS')?'PHAGOCYTOSIS':c.actions.includes('CARGO_PROCESSING')?'CARGO_PROCESSING':'WAIT');await run(t,120,provider);assert(['internalized','killed'].includes(b.state));const event=[...t.kernel.events.values()].find(e=>e.action_id==='PHAGOCYTOSIS'&&e.status==='acknowledged');assert(event);const tx=[...t.appliedTransactions.values()].find(v=>v.plan.event_id===event.id),before=state(t);t.commitCompletion(tx.plan);assert.equal(state(t),before);assert.equal(t.auditLab().bacteria.residual,0);});
test('a lost contact cancels ingestion before energy consumption',async()=>{const t=new UnifiedTissue();t.inject('epec');const c=t.cells.find(c=>c.type==='macrophage'),b=t.lab.bacteria[0];b.x=c.x;b.y=c.y;b.compartment='basal';const p=t.plan(),r=await fixture(c=>c.actions.includes('PHAGOCYTOSIS')?'PHAGOCYTOSIS':'WAIT')(p.request);t.commitChoices(p,r);const e=t.kernel.activeEvents(c.id)[0];assert.equal(e.action_id,'PHAGOCYTOSIS');b.x=.99;b.y=.1;const energy=c.state.resources.energy;t.advancePhysical();assert.equal(t.kernel.getEvent(e.id).status,'cancelled');assert.equal(c.state.resources.energy,energy);assert.equal(b.state,'free');});
test('no autonomous cellular lab events bypass the Jev choices',async()=>{const t=new UnifiedTissue();t.inject('epec');await run(t,60,fixture(()=> 'WAIT'));assert([...t.kernel.events.values()].length===0);assert(t.lab.events.every(e=>e.action_id==='ILEUM_ADHESION'));assert.equal(t.fields.amount('CXCL8'),0);});
test('all recorded cell morphology and replay observations are immutable snapshots',()=>{const t=new UnifiedTissue();t.inject('epec');const f=clone(t.history[0]);t.cells[0].health=50;assert.deepEqual(t.history[0],f);assert(t.history[0].cells.every(c=>c.manual&&c.unified));assert.equal(t.export().mode,'unified');assert.equal(HOST_ACTIONS.length,22);});

test('negative clauses do not add the explicitly absent perturbation',()=>{assert.deepEqual(parsePerturbation('IBD without pathogen').kinds,['ileitis']);assert.equal(parsePerturbation('Lactose without inflammation').valid,false);assert.deepEqual(parsePerturbation('Stop pathogen input').kinds,['resolve']);});

test('shared microbial target is reserved by only one simultaneous Jev choice',async()=>{
 const t=new UnifiedTissue();t.inject('epec');const cs=t.cells.filter(c=>c.type==='macrophage').slice(0,2),b=t.lab.bacteria[0];cs[1].x=cs[0].x;cs[1].y=cs[0].y;b.x=cs[0].x;b.y=cs[0].y;b.compartment='basal';const p=t.plan(),r=await fixture(c=>c.actions.includes('PHAGOCYTOSIS')?'PHAGOCYTOSIS':'WAIT')(p.request);t.commitChoices(p,r);assert.equal([...t.kernel.events.values()].filter(e=>e.action_id==='PHAGOCYTOSIS'&&e.target_id===b.id).length,1);assert.equal(t.decisions.filter(d=>d.rejection).length,1);
});
test('transported cues remain mass-accounted and snapshots do not mutate field storage',async()=>{
 const t=new UnifiedTissue();t.inject('injury');await run(t,40,fixture(()=> 'WAIT'));for(const a of Object.values(t.fields.audit()))assert(Math.abs(a.residual)<1e-9);const before=JSON.stringify(t.fields.values);t.recordFrame(true);assert.equal(JSON.stringify(t.fields.values),before);assert(t.fields.amount('PAMP')>0);
});
test('bounded recovery changes surviving tissue only after a completed manual event',()=>{
 const t=new UnifiedTissue(),c=t.cells[0];c.health=80;t.slots[0].junction=.6;const s=t.snapshot(c),e=t.kernel.start('EPITHELIAL_RECOVERY',s);t.time_min=Math.ceil(e.duration_min);t.tick=t.time_min;t.revision++;const plan=t.kernel.advance(e.id,t.snapshot(c,e),t.time_min);assert(plan.transaction_id);t.commitCompletion({...plan,run_id:t.run_id});assert.equal(c.health,85);assert.equal(t.slots[0].junction,.7);assert.equal(t.cells.length,100);
});
test('stromal and regulatory induction completions create the manual capacity, not immediate secreted mass',()=>{
 for(const [type,id,path,prepare]of [
  ['fibroblast','STROMAL_ACTIVATION','programs',c=>c.state.memory.stromal_alarm=.8],
  ['fibroblast','STROMAL_CXCL8_INDUCTION','outputs',c=>c.state.programs.inflammation=.8],
  ['macrophage','MYELOID_IL10_INDUCTION','outputs',c=>c.state.memory.alarm=.8]]){
  const t=new UnifiedTissue(),c=t.cells.find(c=>c.type===type);prepare(c);const e=t.kernel.start(id,t.snapshot(c));t.time_min=Math.ceil(e.duration_min);t.tick=t.time_min;t.revision++;const p=t.kernel.advance(e.id,t.snapshot(c,e),t.time_min);t.commitCompletion({...p,run_id:t.run_id});const key=id==='STROMAL_ACTIVATION'?'inflammation':id==='STROMAL_CXCL8_INDUCTION'?'CXCL8':'IL10';assert.equal(c.state[path][key],1);assert.equal(t.fields.amount('CXCL8'),0);assert.equal(t.lab.patches[t.nearestPatch(c.x)].IL10,0);
 }
});
test('reserve entry follows a local cue and moves an existing cell without creating a cell',()=>{
 const t=new UnifiedTissue(),c=t.cells.find(c=>c.reserve&&c.type==='neutrophil');t.fields.deposit('CXCL8',t.local(c).fi,.1);const e=t.kernel.start('VASCULAR_CROSSING',t.snapshot(c));t.time_min=Math.ceil(e.duration_min);t.tick=t.time_min;t.revision++;const p=t.kernel.advance(e.id,t.snapshot(c,e),t.time_min);t.commitCompletion({...p,run_id:t.run_id});assert.equal(c.reserve,false);assert.equal(c.lab.compartment,'basal');assert.equal(t.cells.length,100);
});
test('manual junction response increases permeability rather than faking repair',()=>{
 const t=new UnifiedTissue(),c=t.cells[0];c.state.memory.TNF=.8;const e=t.kernel.start('JUNCTION_RESPONSE',t.snapshot(c));t.time_min=Math.ceil(e.duration_min);t.tick=t.time_min;t.revision++;const p=t.kernel.advance(e.id,t.snapshot(c,e),t.time_min);t.commitCompletion({...p,run_id:t.run_id});assert.equal(t.slots[0].junction,.75);
});

test('historical automatic host-cell entrypoints are disabled in the unified host',()=>{const t=new UnifiedTissue();assert.throws(()=>t.step(1));assert.throws(()=>t.advanceOne(1));assert.throws(()=>t.startEvent('ILEUM_PHAGOCYTOSIS','cell-070','epec-1'));});
