import test from 'node:test';
import assert from 'node:assert/strict';
import {UnifiedTissue,parsePerturbation} from '../src/unified-host.mjs';
import {surface} from '../src/engine.mjs';
const choose=action=>async r=>({...r,decisions:Object.fromEntries(r.cells.map(c=>{const a=c.actions.includes(action)?action:'WAIT';return [c.id,{action:a,weights:Object.fromEntries(c.actions.map(k=>[k,Number(k===a)])),confidence:1,source:'Jev'}]})),meta:{model:'fixture-not-live',calls:1}});
function finish(t,c,e,dt=Math.ceil(e.duration_min)){t.time_min+=dt;t.tick+=dt;t.revision++;const p=t.kernel.advance(e.id,t.snapshot(c,e),t.time_min);if(p.transaction_id)t.commitCompletion({...p,run_id:t.run_id});return t.kernel.getEvent(e.id);}
function setupGradient(t,c,key){const fi=t.local(c).fi,x=fi%t.fields.w,y=Math.floor(fi/t.fields.w);for(let j=0;j<t.fields.values[key].length;j++)if(t.fields.side[j]==='basal')t.fields.deposit(key,j,(j%t.fields.w+1)*.002);return fi;}
test('explicit eight identities preserve 100 agents, eight reserves and quiet baseline',()=>{const t=new UnifiedTissue(),counts={};for(const c of t.cells)counts[c.state.type]=(counts[c.state.type]??0)+1;assert.deepEqual(counts,{enterocyte:42,goblet:8,fibroblast:20,resident_macrophage:6,inflammatory_monocyte:4,dendritic:2,neutrophil:10,nk:8});assert.equal(t.metrics.active,0);assert.equal(t.plan().request.cells.length,0);});
test('neutrophil motion uses physical micrometers, a local gradient and a real recorded path',async()=>{const t=new UnifiedTissue(),c=t.cells.find(c=>c.type==='neutrophil'&&!c.reserve);c.x=.5;c.y=.75;setupGradient(t,c,'CXCL8');const before={x:c.x,y:c.y},p=t.plan();t.commitChoices(p,await choose('NEUTROPHIL_CHEMOTAXIS')(p.request));const e=t.kernel.activeEvents(c.id)[0];assert(e);finish(t,c,e);assert(c.x>before.x);assert(c.v5.distance_um>0&&c.v5.distance_um<=4*e.duration_min+1e-8);assert(c.v5.trail.length===2);assert.equal(c.y,before.y);});
test('monocytes use CCL2, never silently reinterpret CXCL8 as CCL2',()=>{const t=new UnifiedTissue(),c=t.cells.find(c=>c.state.type==='inflammatory_monocyte'&&!c.reserve);c.x=.5;c.y=.75;setupGradient(t,c,'CXCL8');assert(!t.candidates(c).find(a=>a.action_id==='MONOCYTE_CHEMOTAXIS').allowed);setupGradient(t,c,'CCL2');assert(t.candidates(c).find(a=>a.action_id==='MONOCYTE_CHEMOTAXIS').allowed);const e=t.kernel.start('MONOCYTE_CHEMOTAXIS',t.snapshot(c));finish(t,c,e);assert(c.v5.distance_um>0);});
test('a disappearing gradient cancels motion and leaves no decorative displacement',()=>{const t=new UnifiedTissue(),c=t.cells.find(c=>c.type==='neutrophil'&&!c.reserve);c.x=.5;c.y=.75;setupGradient(t,c,'CXCL8');const e=t.kernel.start('NEUTROPHIL_CHEMOTAXIS',t.snapshot(c)),x=c.x;t.fields.values.CXCL8.fill(0);finish(t,c,e);assert.equal(c.x,x);assert.equal(c.v5.distance_um,0);assert.equal(t.kernel.getEvent(e.id).status,'cancelled');});
test('monocyte vascular recruitment consumes an existing reserve, using its own cue',()=>{const t=new UnifiedTissue(),c=t.cells.find(c=>c.state.type==='inflammatory_monocyte'&&c.reserve);t.fields.deposit('CCL2',t.local(c).fi,.1);const e=t.kernel.start('VASCULAR_CROSSING',t.snapshot(c));finish(t,c,e);assert(!c.reserve);assert.equal(c.lab.recruitedAt,t.time_min);assert.equal(t.cells.length,100);});
test('CCL2 is a completed manual cellular output with conserved transport',()=>{const t=new UnifiedTissue(),c=t.cells.find(c=>c.state.type==='inflammatory_monocyte'&&!c.reserve);c.state.memory.alarm=.8;const e=t.kernel.start('MYELOID_CCL2_INDUCTION',t.snapshot(c));finish(t,c,e);assert.equal(c.state.outputs.CCL2,1);assert.equal(t.fields.amount('CCL2'),0);t.updateContinuous(1);t.fields.advance(1);assert(t.fields.amount('CCL2')>0);assert(Math.abs(t.fields.audit().CCL2.residual)<1e-10);});
test('Jev-selected severe injury commitment starts mandatory death execution; no revival',async()=>{const t=new UnifiedTissue(),c=t.cells[0];c.health=20;c.state.damage=.8;c.state.viability='injured';const p=t.plan();t.commitChoices(p,await choose('DEATH_COMMITMENT')(p.request));const e=t.kernel.activeEvents(c.id)[0];assert.equal(e.action_id,'DEATH_COMMITMENT');finish(t,c,e);assert.equal(c.state.viability,'death_committed');t.advancePhysical();const terminal=t.kernel.activeEvents(c.id).find(e=>e.action_id==='DEATH_EXECUTION');assert(terminal);assert.equal(c.state.viability,'death_committed');finish(t,c,terminal);assert.equal(c.state.viability,'dead_present');assert(!c.alive&&c.corpse);assert.equal(t.slots[c.slot].junction,0);t.advancePhysical();assert(!c.alive);assert(!t.plan().request.cells.some(q=>q.id===c.visualIndex));});
test('recovering below the death gate cancels commitment instead of forcing mortality',()=>{const t=new UnifiedTissue(),c=t.cells[0];c.health=20;c.state.damage=.8;c.state.viability='injured';const e=t.kernel.start('DEATH_COMMITMENT',t.snapshot(c));c.health=60;c.state.damage=.4;finish(t,c,e);assert.equal(t.kernel.getEvent(e.id).status,'cancelled');assert(c.alive);});
test('a death corpse remains until a real exclusive efferocytosis transaction clears it',()=>{const t=new UnifiedTissue(),c=t.cells[0],m=t.cells.find(c=>c.state.type==='resident_macrophage');t.recordDeath(c,'test injury','fixture');m.x=c.x;m.y=c.y+.01;const e=t.kernel.start('EFFEROCYTOSIS',t.snapshot(m));assert(c.corpse);finish(t,m,e);assert.equal(c.state.viability,'cleared');assert(!c.corpse);assert(m.lab.cargo.includes(`corpse:${c.id}`));});
test('dendritic antigen processing requires real uptake and keeps provenance after digestion',()=>{const t=new UnifiedTissue(),c=t.cells.find(c=>c.state.type==='dendritic');assert(!t.candidates(c).find(a=>a.action_id==='DC_ANTIGEN_PROCESSING').allowed);t.inject('epec',c.x);const b=t.lab.bacteria[0];b.x=c.x;b.y=c.y-.02;const uptake=t.kernel.start('PHAGOCYTOSIS',t.snapshot(c));finish(t,c,uptake);assert.equal(c.v5.antigens[0].id,b.id);assert.equal(c.v5.presented.length,0);const processing=t.kernel.start('DC_ANTIGEN_PROCESSING',t.snapshot(c));const digestion=t.kernel.start('CARGO_PROCESSING',t.snapshot(c));finish(t,c,digestion);assert.equal(b.state,'killed');finish(t,c,processing);assert.equal(c.v5.presented.length,1);assert.equal(c.v5.presented[0].id,b.id);assert.equal(c.v5.presented[0].acquired_at,uptake.duration_min===0?0:Math.ceil(uptake.duration_min));const tx=[...t.appliedTransactions.values()].find(tx=>tx.plan.event_id===processing.id);t.commitCompletion(tx.plan);assert.equal(c.v5.presented.length,1);assert.equal(t.auditLab().bacteria.residual,0);});
test('dendrites cannot acquire remote luminal bacteria',()=>{const t=new UnifiedTissue(),c=t.cells.find(c=>c.state.type==='dendritic');t.inject('epec',.8);assert.equal(t.local(c).bacteria.length,0);assert(!t.candidates(c).find(a=>a.action_id==='PHAGOCYTOSIS').allowed);});
test('adaptation is a days-long phenotype transition, preserves monocyte origin, and pauses under alarm',()=>{const t=new UnifiedTissue(),c=t.cells.find(c=>c.state.type==='inflammatory_monocyte'&&!c.reserve);assert(!t.candidates(c).find(a=>a.action_id==='MYELOID_ADAPTATION').allowed);c.lab.recruitedAt=0;const e=t.kernel.start('MYELOID_ADAPTATION',t.snapshot(c));assert(e.duration_min>=1440);t.fields.deposit('TNF',t.local(c).fi,1);finish(t,c,e,20);assert.equal(t.kernel.getEvent(e.id).status,'paused');assert.equal(t.kernel.getEvent(e.id).active_elapsed_min,0);t.fields.values.TNF.fill(0);finish(t,c,e);assert.equal(c.v5.phenotype,'resident_like');assert.equal(c.v5.origin,'inflammatory_monocyte');assert.equal(c.state.type,'inflammatory_monocyte');assert.equal(c.v5.transitions.length,1);assert(!t.candidates(c).find(a=>a.action_id==='MYELOID_ADAPTATION').allowed);});
test('new biology is snapshot-only during replay; original manual stays authoritative',()=>{const t=new UnifiedTissue(),c=t.cells[0];t.recordFrame(true);const f=structuredClone(t.history.at(-1));t.recordDeath(c,'fixture','fixture');assert.deepEqual(t.history.at(-1),f);assert.equal(t.export().coverage.manual_handlers.length,22);});
