import fs from 'node:fs';
import assert from 'node:assert/strict';
import {RuleKernel,RuleError,validateRegistry,evaluatePredicate,writePath,readPath,parameter,seededRandom,sampleDuration,sampleCompeting,eventProbability,exactMemory,receptorActivity,boundedFlux,diffuse2D,validateProviderResponse} from './virtual_tissue_kernel.mjs';
const registry=JSON.parse(fs.readFileSync(new URL('./virtual_tissue_rules_v2.json',import.meta.url)));
const caps=[...registry.host_contract.required_for_any_execution,...registry.host_contract.optional_capabilities];
const report=[];
const test=(name,fn)=>{try{fn();report.push({name,passed:true});console.log(`PASS ${name}`);}catch(e){report.push({name,passed:false,error:e.message});console.error(`FAIL ${name}: ${e.stack}`);}};
const expectCode=(fn,code)=>assert.throws(fn,e=>e instanceof RuleError&&e.code===code);
function satisfy(p,s){if(p.all)p.all.forEach(q=>satisfy(q,s));else if(p.any)satisfy(p.any[0],s);else {const v=p.param?parameter(registry,p.param):p.value;let result=v;if(p.op==='in')result=v[0];if(p.op==='lt')result=v-.01;if(p.op==='gt')result=v+.01;writePath(s,p.path,result);}}
function fixture(actionId, id='cell_1'){
 const a=registry.actions.find(x=>x.id===actionId);
 const s={tick:0,revision:0,time_min:0,cell:{id,type:a.cell_types[0],viability:'viable',resources:{energy:1,phagocytic_capacity:1},stores:{granules:1,cytotoxic:1,pro_IL1B:1},outputs:{CXCL8:0},competence:{},programs:{},memory:{},cycle:{ready:true,completed_rounds:0},damage:0},context:{target_id:'target_1',crossing_slot_id:'venule_1',species:'human'},signals:{}};
 for(const t of a.hazard.terms)writePath(s,t.path,0.6);
 satisfy(a.gate,s);satisfy(a.trigger,s);s.cell.resources.energy=1;
 for(const c of a.costs)writePath(s,c.path,Math.max(1,readPath(s,c.path)??0));
 return s;
}
const kernel=()=>new RuleKernel(registry,{seed:714,capabilities:caps});
function completed(k,id='GOBLET_RELEASE'){
 const s=fixture(id),e=k.start(id,s),later=structuredClone(s);later.time_min=e.duration_min+1;
 const plan=k.advance(e.id,later,later.time_min);return{k,s,e,later,plan};
}
test('registry references and roster contracts',()=>{assert.equal(validateRegistry(registry).actions,55);for(const x of Object.values(registry.initial_presets))assert.equal(Object.values(x).reduce((a,b)=>a+b,0),100);});
test('proposed parameters never represented as fitted',()=>{assert(Object.values(registry.parameters).every(p=>p.evidence==='P'&&!p.calibrated&&!p.source_supplies_value));});
test('research execution rejected',()=>expectCode(()=>new RuleKernel(registry,{profile:'research',capabilities:caps}),'UNCALIBRATED_RESEARCH_MODE'));
test('mature enterocyte cannot start a stem cycle',()=>{const s=fixture('ISC_CYCLE');s.cell.type='enterocyte';assert.equal(kernel().eligibility('ISC_CYCLE',s).allowed,false);});
test('high score cannot override failed lineage or receptor gate',()=>{const s=fixture('EPITHELIAL_CXCL8_INDUCTION');s.cell.competence.CXCL8_output=false;s.cell.memory.alarm=100;assert.equal(kernel().eligibility('EPITHELIAL_CXCL8_INDUCTION',s).allowed,false);});
test('missing receptor competence denies rather than assumes zero or presence',()=>{const s=fixture('EPITHELIAL_CXCL8_INDUCTION');delete s.cell.competence.CXCL8_output;assert.equal(kernel().eligibility('EPITHELIAL_CXCL8_INDUCTION',s).allowed,false);});
test('missing score value is an explicit error',()=>{const s=fixture('ISC_CYCLE');delete s.cell.damage;expectCode(()=>kernel().eligibility('ISC_CYCLE',s),'MISSING_SCORE_FEATURE');});
test('absent physical capability rejects action',()=>{const s=fixture('GOBLET_RELEASE');assert.equal(new RuleKernel(registry).eligibility('GOBLET_RELEASE',s).allowed,false);});
test('human intracellular sensing cannot read luminal exposure',()=>{const s=fixture('HUMAN_INTRACELLULAR_ALARM');s.context.intracellular_ligand_access=false;s.signals.luminal_pathogen=1;assert.equal(kernel().eligibility('HUMAN_INTRACELLULAR_ALARM',s).allowed,false);});
test('mouse overlay disabled in human default',()=>{const s=fixture('MOUSE_NLRC4_ALARM');s.context.species='human';assert.equal(kernel().eligibility('MOUSE_NLRC4_ALARM',s).allowed,false);});
test('new stem cycle cannot complete in two minutes',()=>{const k=kernel(),s=fixture('ISC_CYCLE'),e=k.start('ISC_CYCLE',s);const n={...s,time_min:2};const out=k.advance(e.id,n,2);assert.equal(out.status,'running');assert(out.active_elapsed_min<out.duration_min);});
test('historical duration cannot bypass the versioned prior',()=>{expectCode(()=>kernel().start('ISC_CYCLE',fixture('ISC_CYCLE'),{initialized_duration:2}),'DURATION_OUTSIDE_PRIOR');});
test('an advanced historical cycle can complete shortly after time zero',()=>{const k=kernel(),s=fixture('ISC_CYCLE'),e=k.start('ISC_CYCLE',s,{initialized_duration:1440,initialized_elapsed:1439});assert.equal(k.advance(e.id,{...s,time_min:1},1).transaction_id,`${e.id}:complete`);});
test('event duration sampled once and retained',()=>{const k=kernel(),s=fixture('ISC_CYCLE'),e=k.start('ISC_CYCLE',s);k.advance(e.id,{...s,time_min:30},30);assert.equal(k.getEvent(e.id).duration_min,e.duration_min);});
test('cycle completion does not receive a second initiation lottery',()=>{const k=kernel(),s=fixture('ISC_CYCLE'),e=k.start('ISC_CYCLE',s);const p=k.advance(e.id,{...s,time_min:e.duration_min},e.duration_min);assert.equal(p.action_id,'ISC_CYCLE');});
test('lost niche pauses cycle without resetting it',()=>{const k=kernel(),s=fixture('ISC_CYCLE'),e=k.start('ISC_CYCLE',s);k.advance(e.id,{...s,time_min:10},10);const weak=structuredClone(s);weak.time_min=40;weak.context.niche_support=0;assert.equal(k.advance(e.id,weak,40).status,'paused');const back=structuredClone(s);back.time_min=50;assert.equal(k.advance(e.id,back,50).active_elapsed_min,20);});
test('death cancels incompatible active cycle',()=>{const k=kernel(),s=fixture('ISC_CYCLE'),e=k.start('ISC_CYCLE',s);const n=structuredClone(s);n.cell.viability='death_committed';n.time_min=10;assert.equal(k.advance(e.id,n,10).status,'cancelled');});
test('committed death execution is scheduled automatically',()=>{const k=kernel(),s=fixture('DEATH_EXECUTION'),p=k.plan(s,1);assert(p.some(x=>x.action_id==='DEATH_EXECUTION'&&x.waiting_minutes===0));});
test('cleared cells cannot act',()=>{const k=kernel(),s=fixture('GOBLET_RELEASE');s.cell.viability='cleared';assert(!k.eligibility('GOBLET_RELEASE',s).allowed);});
test('empty granule store cannot release',()=>{const k=kernel(),s=fixture('GOBLET_RELEASE');s.cell.stores.granules=0;assert(!k.eligibility('GOBLET_RELEASE',s).allowed);});
test('two phagocytes cannot reserve one corpse',()=>{const k=kernel(),s=fixture('EFFEROCYTOSIS','mac_1');k.start('EFFEROCYTOSIS',s);const s2=fixture('EFFEROCYTOSIS','mac_2');assert(k.eligibility('EFFEROCYTOSIS',s2).reasons.includes('TARGET_UNAVAILABLE'));});
test('target reservation survives ongoing contact and does not cancel itself',()=>{const k=kernel(),s=fixture('EFFEROCYTOSIS'),e=k.start('EFFEROCYTOSIS',s);s.context.target_unreserved=false;s.time_min=1;assert.equal(k.advance(e.id,s,1).status,'running');});
test('contact loss cancels engulfment and releases reservations',()=>{const k=kernel(),s=fixture('EFFEROCYTOSIS'),e=k.start('EFFEROCYTOSIS',s);s.context.valid_contact=false;s.time_min=1;assert.equal(k.advance(e.id,s,1).status,'cancelled');assert(!k.targetOwners.has('target_1'));});
test('secretion and motility use separate action channels',()=>{const k=kernel(),s=fixture('MYELOID_CCL2_INDUCTION');const motion=registry.actions.find(a=>a.id==='MONOCYTE_CHEMOTAXIS');satisfy(motion.gate,s);satisfy(motion.trigger,s);for(const x of motion.hazard.terms)writePath(s,x.path,.8);s.cell.resources.energy=1;k.start('MYELOID_CCL2_INDUCTION',s);assert(k.eligibility('MONOCYTE_CHEMOTAXIS',s).allowed);});
test('vascular entry requires reservoir origin and a crossing slot',()=>{const k=kernel(),s=fixture('VASCULAR_CROSSING');s.context.compartment='lamina_propria';assert(!k.eligibility('VASCULAR_CROSSING',s).allowed);});
test('two cells cannot own one vascular crossing slot',()=>{const k=kernel(),s=fixture('VASCULAR_CROSSING','n1');k.start('VASCULAR_CROSSING',s);const s2=fixture('VASCULAR_CROSSING','n2');assert(k.eligibility('VASCULAR_CROSSING',s2).reasons.includes('CROSSING_SLOT_RESERVED'));});
test('effects stay pending without an atomic host receipt',()=>{const{k,e,plan}=completed(kernel());assert.equal(k.getEvent(e.id).status,'pending');expectCode(()=>k.acknowledge(e.id,{committed:false}),'BAD_RECEIPT');assert.equal(k.getEvent(e.id).status,'pending');assert.equal(plan.effects[0].kind,'stored_release');});
test('completion is acknowledged only once',()=>{const{k,e,later,plan}=completed(kernel());const receipt={committed:true,transaction_id:plan.transaction_id,next_revision:1,applied_at:later.time_min};assert(!k.acknowledge(e.id,receipt).already_acknowledged);assert(k.acknowledge(e.id,receipt).already_acknowledged);});
test('old snapshot cannot spend already consumed stores again',()=>{const{k,e,s,later,plan}=completed(kernel());k.acknowledge(e.id,{committed:true,transaction_id:plan.transaction_id,next_revision:1,applied_at:later.time_min});expectCode(()=>k.eligibility('GOBLET_RELEASE',s),'STALE_SNAPSHOT');});
test('stored release emits the exact reserved store amount',()=>{const{k,plan}=completed(kernel());const eff=plan.effects.find(e=>e.kind==='stored_release');const b=plan.reserved_costs.find(x=>x.path===eff.arguments.amount_from_reserved_path);assert(b.amount>0);assert.equal(eff.arguments.fraction_ref,undefined);});
test('fixed hazards have algebraic timestep invariance',()=>{const p1=eventProbability(.03,1),p2=eventProbability(.03,2);assert(Math.abs(p2-(1-(1-p1)**2))<1e-14);});
test('Monte Carlo event probability matches the declared hazard',()=>{const rng=seededRandom(481);let n=0;const N=50000;for(let i=0;i<N;i++)if(sampleCompeting([{action_id:'a',hazard_per_minute:.02},{action_id:'b',hazard_per_minute:.01}],10,rng))n++;assert(Math.abs(n/N-eventProbability(.03,10))<.01);});
test('all duration draws stay inside declared demonstration supports',()=>{const rng=seededRandom(12);for(const m of Object.values(registry.duration_models))for(let i=0;i<500;i++){const t=sampleDuration(m,rng);assert(t>=m.lower&&t<=m.upper);}});
test('exposure memory has exact semigroup behavior',()=>{const one=exactMemory(0,1,60,60),two=exactMemory(exactMemory(0,1,60,30),1,60,30);assert(Math.abs(one-two)<1e-14);assert(Math.abs(one-(1-Math.exp(-1)))<1e-14);});
test('receptor response uses competence and concentration rather than hidden distance',()=>{assert.equal(receptorActivity(.5,.5,1,1),.5);assert.equal(receptorActivity(50,.5,1,0),0);expectCode(()=>receptorActivity(1,.5,1,null),'UNKNOWN_COMPETENCE');});
test('secretory flux is rate times elapsed time and bounded by substrate',()=>{const x=boundedFlux(.1,1,30,2);assert.equal(x.amount,2);assert.equal(x.substrate_remaining,0);});
test('diffusion preserves mass under closed boundaries',()=>{const v=new Float64Array(25);v[12]=1;const out=diffuse2D(v,5,5,{D:100,dx:10,dt:1});assert(out.substeps>1);assert(Math.abs(out.amount_after_proportional-1)<1e-12);assert([...out.values].every(x=>x>=0));});
test('diffusion with decay reproduces total half life',()=>{const v=new Float64Array(9).fill(1);const out=diffuse2D(v,3,3,{D:100,dx:10,dt:30,decay:Math.log(2)/30});assert(Math.abs(out.amount_after_proportional-4.5)<1e-10);});
test('unsafe predicate path is rejected without eval',()=>expectCode(()=>readPath({},'cell.__proto__.x'),'UNSAFE_PATH'));
test('nonfinite input is rejected',()=>expectCode(()=>eventProbability(NaN,1),'NONFINITE_VALUE'));
test('stale model response is rejected',()=>{const b={tick:3,revision:7,cells:[{id:'a',allowed:['GOBLET_RELEASE'],channels:{GOBLET_RELEASE:'exocytosis'}}]};expectCode(()=>validateProviderResponse(b,{tick:3,revision:6,decisions:[]}),'STALE_PROVIDER_RESPONSE');});
test('model cannot invent actions or set durations',()=>{const b={tick:3,revision:7,cells:[{id:'a',allowed:['GOBLET_RELEASE'],channels:{GOBLET_RELEASE:'exocytosis'}}]};expectCode(()=>validateProviderResponse(b,{tick:3,revision:7,decisions:[{id:'a',choice:'DIVIDE'}]}),'PROVIDER_UNLICENSED_ACTION');expectCode(()=>validateProviderResponse(b,{tick:3,revision:7,decisions:[{id:'a',choice:'GOBLET_RELEASE',channel:'exocytosis',duration:0}]}),'PROVIDER_OWNS_FORBIDDEN_FIELD');});
test('duplicate model decisions are rejected',()=>{const b={tick:3,revision:7,cells:[{id:'a',allowed:['GOBLET_RELEASE']}]};const d={id:'a',choice:'GOBLET_RELEASE'};expectCode(()=>validateProviderResponse(b,{tick:3,revision:7,decisions:[d,d]}),'BAD_PROVIDER_CELL');});
const result={suite:'Virtual tissue kernel contract tests',version:'2.0.0',runtime:process.version,date:'2026-09-19',passed:report.filter(x=>x.passed).length,failed:report.filter(x=>!x.passed).length,tests:report,scope:'Software tests, using synthetic inputs and mock host receipts. Not validation of tissue mechanics, disease behavior, biological parameters or clinical prediction.'};
fs.writeFileSync(new URL('./test_report.json',import.meta.url),JSON.stringify(result,null,2)+'\n');
const example=fixture('EPITHELIAL_CXCL8_INDUCTION');example.cell.id='example_enterocyte';example.cell.type='enterocyte';example.provenance={source_kind:'proposed_prior',uncertainty:'unfitted demonstration fixture',scope:'one cell rule test, not measured tissue'};
fs.writeFileSync(new URL('./example_snapshot.json',import.meta.url),JSON.stringify(example,null,2)+'\n');
if(result.failed)process.exitCode=1;console.log(`${result.passed} passed; ${result.failed} failed.`);
